name: IceWallSpawn
version: 1.0
author: test
main: me.test.IceWall.Main
api-version: 1.13

commands:
  IceWallSpawn:
    aliases: [IceWallSpawn]
    description: /IceWallSpawn to enable snowball walls